version: 2

# Build environment and dependencies
build:
  image: latest

# Documentation build configuration
sphinx:
  configuration: docs/conf.py

# Required Python version
python:
  version: 3.7

# Documentation versions and formats
formats: all